services:
  - type: web
    name: omeka
    runtime: php
    buildCommand: "./render-build.sh"
    startCommand: "apache2-foreground"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: omeka_db
          property: connectionString
